# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159871795a052c586db425cd08ec0a3dc3b45d89026084913551055232cb5b4c9990b5ee0e8fe97127f7fe837e70211946343abcdeb37aaef816f7aced7d7e63

test:
  secret_key_base: c56ae726b7fc85ba070260b2001a96bb9d052dc7f4694c25226da7e6914f42cbd78c88e8da9dbfc5267a20c9bcbdbebb2dfd475c1ae4316d16ffc5f10bae920c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
